#!/usr/bin/env bash
# Verifica que un commit (o conjunto de commits) no introduzca firmas
# externas en líneas agregadas del diff. Solo evalúa adiciones (líneas
# con prefijo `+` en el diff), no eliminaciones — la limpieza de
# contenido previamente existente no constituye violación.
#
# Uso:
#   ./scripts/verify-clean-commits.sh                  # verifica commit staged
#   ./scripts/verify-clean-commits.sh main..HEAD       # verifica un rango
#
# Salida: imprime matches (cero esperado). Si hay matches, sale con
# código 1 para integrarse en pre-commit hooks o pipelines.

set -euo pipefail

RANGE="${1:-}"

if [ -z "$RANGE" ]; then
  DIFF=$(git diff --cached | grep '^+' || true)
else
  DIFF=$(git log -p "$RANGE" | grep '^+' || true)
fi

PATTERN='claude|anthropic|generated with|generated by|co-authored.*claude|🤖|AI[- ]?assist|made with claude|cursor|copilot|codeium|AI[- ]?generated'

MATCHES=$(echo "$DIFF" | grep -iE "$PATTERN" || true)

if [ -n "$MATCHES" ]; then
  echo "VIOLACIÓN: firmas externas detectadas"
  echo "$MATCHES"
  exit 1
else
  echo "OK: cero firmas externas detectadas"
  exit 0
fi
